---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080       # Port interne dans le cluster
      targetPort: 8080 # Port du container
  type: ClusterIP      # Accessible depuis d'autres pods seulement