---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 8080        # Port interne du service
      targetPort: 8080  # Port du container Jenkins
      nodePort: 30080   # Port exposé sur le node
      protocol: TCP     # Optionnel, TCP par défaut